In [6]:
import numpy as np
import pandas as pd
%config Completer.use_jedi = False  # For jupyter notebook autocomplete

In [127]:
obrist = pd.read_excel('./Obrist2014_Smell.xlsx', sheet_name='Sheet1')

In [128]:
obrist.columns, obrist.shape

(Index(['lfdn', 'code_FirstLevel', 'code_SecondLevel', 'CodeNr',
        'AttrakDiffResponses', 'browser', 'CountriesGrowUp_1',
        'CountriesGrowUp_2', 'CountriesGrowUp_3', 'CountriesLived_1',
        ...
        'Parenth', 'OtherP', 'AllPct', 'Cluster_ChreaOdorAffect',
        'Cluster_ChreaOdorAffectItems', 'Cluster_ChreaOdorFeaturesItems',
        'Cluster_AffectItems', 'filter_$', 'Codes_X_ClusterOdorQuality',
        'Quality_X_OdorAffectCluster'],
       dtype='object', length=402),
 (439, 402))

In [129]:
obrist = obrist[['code_FirstLevel', 'code_SecondLevel', 'T_TitleOfExp', 'T_Trigger', 'WordCount', 'T_Valence', 'T_Valence_dichotom', 'Codes_X_ClusterOdorQuality']]

In [130]:
obrist

,code_FirstLevel,code_SecondLevel,T_TitleOfExp,T_Trigger,WordCount,T_Valence,T_Valence_dichotom,Codes_X_ClusterOdorQuality
0,affecting,affected the social interaction/togetherness,It Wasn't Gas I Passed,The smell was in comparison to rotten eggs and...,92,-2,negative,Cluster 1 penetrating -- affected the social ...
1,affecting,affected the social interaction/togetherness,The Foul Litter box,Whenever I walked into my brother's apartment ...,171,-4,negative,Cluster 1 penetrating -- affected the social ...
2,affecting,affected the social interaction/togetherness,I Can't Smell You,"I, just tonight, had a coworker fart in my off...",103,-4,negative,Cluster 1 penetrating -- affected the social ...
3,affecting,affected the social interaction/togetherness,Dragon Breath Teacher,Once a teacher yelled at me during class. She ...,53,-4,negative,Cluster 1 penetrating -- affected the social ...
4,affecting,affected the social interaction/togetherness,The day I took a plunge,I was playing in a field with my friends when ...,78,-4,negative,Cluster 1 penetrating -- affected the social ...
...,...,...,...,...,...,...,...,...
434,stimulating,triggered newness,New car smell,One particular smell experience I remember is ...,72,4,positive,Cluster 5 attractive -- triggered newness
435,stimulating,triggered newness,New Purse,I had been obsessing over a Marc Jacobs purse ...,112,4,positive,Cluster 5 attractive -- triggered newness
436,stimulating,triggered newness,Building a PC: A newcomer's experience,I was unpacking the components of my new compu...,92,4,positive,Cluster 5 attractive -- triggered newness
437,stimulating,caused an aha-moment,Scent of Skin,"Smell of the skin, when growing up I heard muc...",64,3,positive,Cluster 5 attractive -- caused an aha-moment
438,stimulating,caused an aha-moment,Coffee Reborn,"The first time I walked into SteamDot, the fin...",160,4,positive,Cluster 5 attractive -- caused an aha-moment

In [131]:
# Interim result saved for later use
obrist.to_csv('./obrist_interest_cols.csv', index=False)

## Making df_text

In [12]:
obrist_text = obrist[['T_TitleOfExp', 'T_Trigger']]
obrist_text.columns = ['title', 'trigger']

In [13]:
obrist_text

,title,trigger
0,It Wasn't Gas I Passed,The smell was in comparison to rotten eggs and...
1,The Foul Litter box,Whenever I walked into my brother's apartment ...
2,I Can't Smell You,"I, just tonight, had a coworker fart in my off..."
3,Dragon Breath Teacher,Once a teacher yelled at me during class. She ...
4,The day I took a plunge,I was playing in a field with my friends when ...
...,...,...
434,New car smell,One particular smell experience I remember is ...
435,New Purse,I had been obsessing over a Marc Jacobs purse ...
436,Building a PC: A newcomer's experience,I was unpacking the components of my new compu...
437,Scent of Skin,"Smell of the skin, when growing up I heard muc..."
438,Coffee Reborn,"The first time I walked into SteamDot, the fin..."

In [14]:
# Create an empty df for better computation speed
indices = [x for x in range(len(obrist_text))]
df_text = pd.DataFrame(columns=['text'], index=indices)

In [15]:
# Now doing row-wise combinination of title and text
for index, row in obrist_text.iterrows():
    df_text.iloc[index]['text'] = (row.title).strip() + ". " + (row.trigger).strip()

In [16]:
df_text

                                                  text
0    It Wasn't Gas I Passed. The smell was in compa...
1    The Foul Litter box. Whenever I walked into my...
2    I Can't Smell You. I, just tonight, had a cowo...
3    Dragon Breath Teacher. Once a teacher yelled a...
4    The day I took a plunge. I was playing in a fi...
..                                                 ...
434  New car smell. One particular smell experience...
435  New Purse. I had been obsessing over a Marc Ja...
436  Building a PC: A newcomer's experience. I was ...
437  Scent of Skin. Smell of the skin, when growing...
438  Coffee Reborn. The first time I walked into St...

[439 rows x 1 columns]

In [17]:
# Interim result saved for later use
df_text.to_csv('./obrist_text.csv', index=False)

## Making df_chrea_obrist-ground_truth

In [23]:
df_chrea_obrist = obrist[['Codes_X_ClusterOdorQuality']]
df_chrea_obrist.columns = ['cluster']

In [24]:
df_chrea_obrist = pd.concat([df_text, df_chrea_obrist], axis=1)
df_chrea_obrist

,text,cluster
0,It Wasn't Gas I Passed. The smell was in compa...,Cluster 1 penetrating -- affected the social ...
1,The Foul Litter box. Whenever I walked into my...,Cluster 1 penetrating -- affected the social ...
2,"I Can't Smell You. I, just tonight, had a cowo...",Cluster 1 penetrating -- affected the social ...
3,Dragon Breath Teacher. Once a teacher yelled a...,Cluster 1 penetrating -- affected the social ...
4,The day I took a plunge. I was playing in a fi...,Cluster 1 penetrating -- affected the social ...
...,...,...
434,New car smell. One particular smell experience...,Cluster 5 attractive -- triggered newness
435,New Purse. I had been obsessing over a Marc Ja...,Cluster 5 attractive -- triggered newness
436,Building a PC: A newcomer's experience. I was ...,Cluster 5 attractive -- triggered newness
437,"Scent of Skin. Smell of the skin, when growing...",Cluster 5 attractive -- caused an aha-moment
438,Coffee Reborn. The first time I walked into St...,Cluster 5 attractive -- caused an aha-moment

In [27]:
df_chrea_obrist['cluster'].unique()

array(['Cluster 1 penetrating --  affected the social interaction/togetherness',
       'Cluster 2 nauseous -- affected the social interaction/togetherness',
       'Cluster 3 fresh -- affected the social interaction/togetherness',
       'Cluster 4 mouthwatering -- affected the social interaction/togetherness',
       'Cluster 1 penetrating --  made me change my behaviour',
       'Cluster 2 nauseous -- made me change my mood',
       'Cluster 3 fresh -- made me change my behaviour',
       'Cluster 3 fresh -- made me change my mood',
       'Cluster 3 fresh -- has been used to change the mood',
       'Cluster 4 mouthwatering -- changed my attitude',
       'Cluster 4 mouthwatering -- made me change my behaviour',
       'Cluster 4 mouthwatering -- made me change my mood',
       'Cluster 1 penetrating --  linked to a location',
       'Cluster 1 penetrating --  linked to a negative event/episode',
       'Cluster 1 penetrating --  linked to a negative life event',
       'Cluster 2 nauseous -- coupled to a person',
       'Cluster 2 nauseous -- linked to a location',
       'Cluster 2 nauseous -- linked to a tradition',
       'Cluster 2 nauseous -- linked to a negative event/episode',
       'Cluster 2 nauseous -- linked to a negative life event',
       'Cluster 2 nauseous -- linked to a positive event/episode',
       'Cluster 2 nauseous -- linked to a positive life event',
       'Cluster 3 fresh -- coupled to first time encounter with a person',
       'Cluster 3 fresh -- coupled to a person',
       'Cluster 3 fresh -- coupled to achievement/success',
       'Cluster 3 fresh -- linked to a new beginning',
       'Cluster 3 fresh -- linked to a location',
       'Cluster 3 fresh -- linked to a tradition',
       'Cluster 3 fresh -- linked to a negative life event',
       'Cluster 3 fresh -- linked to a positive event/episode',
       'Cluster 3 fresh -- linked to a positive life event',
       'Cluster 4 mouthwatering -- coupled to a person',
       'Cluster 4 mouthwatering -- coupled to achievement/success',
       'Cluster 4 mouthwatering -- linked to a new beginning',
       'Cluster 4 mouthwatering -- linked to a location',
       'Cluster 4 mouthwatering -- linked to a tradition',
       'Cluster 4 mouthwatering -- linked to a negative event/episode',
       'Cluster 4 mouthwatering -- linked to a negative life event',
       'Cluster 4 mouthwatering -- linked to a positive event/episode',
       'Cluster 4 mouthwatering -- linked to a positive life event',
       'Cluster 5 attractive -- coupled to first time encounter with a person',
       'Cluster 5 attractive -- coupled to a person',
       'Cluster 5 attractive -- linked to a new beginning',
       'Cluster 5 attractive -- linked to a location',
       'Cluster 5 attractive -- linked to a tradition',
       'Cluster 5 attractive -- linked to a negative event/episode',
       'Cluster 5 attractive -- linked to a positive event/episode',
       'Cluster 5 attractive -- linked to a positive life event',
       'Cluster 1 penetrating --  helped me to identify it',
       'Cluster 1 penetrating --  helped me to detect something',
       'Cluster 2 nauseous -- helped me to identify it',
       'Cluster 2 nauseous -- helped me to detect something',
       'Cluster 3 fresh -- helped me to identify it',
       'Cluster 4 mouthwatering -- helped me to identify it',
       'Cluster 1 penetrating --  surprised me',
       'Cluster 2 nauseous -- builds up expectations',
       'Cluster 2 nauseous -- surprised me',
       'Cluster 3 fresh -- builds up expectations',
       'Cluster 3 fresh -- surprised me',
       'Cluster 4 mouthwatering -- builds up expectations',
       'Cluster 4 mouthwatering -- surprised me',
       'Cluster 5 attractive -- builds up expectations',
       'Cluster 5 attractive -- surprised me',
       'Cluster 1 penetrating --  traumatized me',
       'Cluster 1 penetrating --  overwhelmed me',
       'Cluster 2 nauseous -- traumatized me',
       'Cluster 2 nauseous -- overwhelmed me',
       'Cluster 3 fresh -- traumatized me',
       'Cluster 3 fresh -- overwhelmed me',
       'Cluster 4 mouthwatering -- overwhelmed me',
       'Cluster 1 penetrating --  invaded public space',
       'Cluster 1 penetrating --  invaded private space',
       'Cluster 2 nauseous -- invaded public space',
       'Cluster 2 nauseous -- invaded private space',
       'Cluster 3 fresh -- invaded private space',
       'Cluster 4 mouthwatering -- invaded public space',
       'Cluster 4 mouthwatering -- invaded private space',
       'Cluster 2 nauseous -- due to first time natural scent',
       'Cluster 2 nauseous -- sourced by nature',
       'Cluster 2 nauseous -- sourced by food',
       'Cluster 3 fresh -- due to first time natural scent',
       'Cluster 3 fresh -- sourced by nature',
       'Cluster 3 fresh -- due to first time food',
       'Cluster 3 fresh -- sourced by food',
       'Cluster 3 fresh -- first time perfume scent',
       'Cluster 3 fresh -- sourced by a perfume',
       'Cluster 4 mouthwatering -- sourced by nature',
       'Cluster 4 mouthwatering -- due to first time food',
       'Cluster 4 mouthwatering -- sourced by food',
       'Cluster 4 mouthwatering -- first time perfume scent',
       'Cluster 4 mouthwatering -- sourced by a perfume',
       'Cluster 5 attractive -- due to first time natural scent',
       'Cluster 5 attractive -- sourced by nature',
       'Cluster 5 attractive -- due to first time food',
       'Cluster 5 attractive -- sourced by food',
       'Cluster 5 attractive -- first time perfume scent',
       'Cluster 5 attractive -- sourced by a perfume',
       'Cluster 2 nauseous -- made me remember a location',
       'Cluster 2 nauseous -- made me remember childhood',
       'Cluster 3 fresh -- made me remember a location',
       'Cluster 3 fresh -- made me remember a person',
       'Cluster 3 fresh -- made me remember old times teenager/college',
       'Cluster 3 fresh -- made me remember childhood',
       'Cluster 3 fresh -- triggered a flashback',
       'Cluster 4 mouthwatering -- made me remember a person',
       'Cluster 4 mouthwatering -- made me remember old times teenager/college',
       'Cluster 4 mouthwatering -- made me remember childhood',
       'Cluster 4 mouthwatering -- triggered a flashback',
       'Cluster 5 attractive -- made me remember old times teenager/college',
       'Cluster 5 attractive -- triggered a flashback',
       'Cluster 2 nauseous -- made me fancy something',
       'Cluster 2 nauseous -- triggered newness',
       'Cluster 2 nauseous -- triggered reflection',
       'Cluster 3 fresh -- made me do something',
       'Cluster 3 fresh -- made me fancy something',
       'Cluster 3 fresh -- triggered newness',
       'Cluster 4 mouthwatering -- triggered appetite',
       'Cluster 4 mouthwatering -- made me do something',
       'Cluster 4 mouthwatering -- made me fancy something',
       'Cluster 4 mouthwatering -- triggered newness',
       'Cluster 4 mouthwatering -- caused an aha-moment',
       'Cluster 5 attractive -- triggered appetite',
       'Cluster 5 attractive -- made me do something',
       'Cluster 5 attractive -- made me fancy something',
       'Cluster 5 attractive -- triggered newness',
       'Cluster 5 attractive -- caused an aha-moment'], dtype=object)

In [28]:
len(df_chrea_obrist['cluster'].unique())

126

In [30]:
df_cluster_community = pd.DataFrame(columns=['text', 'clusterID', 'communityID'], index=[x for x in range(len(df_chrea_obrist))])
df_cluster_community

    text clusterID communityID
0    NaN       NaN         NaN
1    NaN       NaN         NaN
2    NaN       NaN         NaN
3    NaN       NaN         NaN
4    NaN       NaN         NaN
..   ...       ...         ...
434  NaN       NaN         NaN
435  NaN       NaN         NaN
436  NaN       NaN         NaN
437  NaN       NaN         NaN
438  NaN       NaN         NaN

[439 rows x 3 columns]

In [31]:
cluster_dict = {}
cluster_comm_dict = {}

def extract_cluster_community(clusterText):
    global cluster_dict, cluster_comm_dict
    splitted = clusterText.split("--")
    cluster, comm = splitted[0].strip(), splitted[1].strip()
    cluster_splitted = [s for s in cluster.split()]
    
    current_cluster = 0
    
    ## Update cluster_dict ##
    try:
        (cluster_splitted[1]).isdigit()
        cluster_id = cluster_splitted[1]
    except:
        raise Exception("cluster number is not a digit")
    
    cluster_meaning = cluster_splitted[2]
    
    if cluster_id not in cluster_dict:
        cluster_dict.update({cluster_id: cluster_meaning})
    else:
        # cluster_id exist in cluster_dict
        if cluster_meaning != cluster_dict[cluster_id]:
            # We do not expect this part to be executed
            raise Exception("same cluster number but different description?")
    
    current_cluster = cluster_id
    
    ## Update cluster_comm_dict ##
    if current_cluster not in cluster_comm_dict:
        cluster_comm_dict.update({current_cluster: {1: comm}})
        # comm_id looks like 1-1, 1-2 ...
        comm_id = f'{current_cluster}-1'
    else:
        comm_dict = cluster_comm_dict.get(current_cluster)
        if comm in comm_dict.values():
            # comm_id looks like 1-1, 1-2 ...
            comm_id = f'{current_cluster}-{list(comm_dict.keys())[list(comm_dict.values()).index(comm)]}'
        else: # comm not in comm_dict values
            new_comm_dict_key = len(comm_dict)+1
            cluster_comm_dict[current_cluster].update({new_comm_dict_key : comm})
            comm_id = f'{current_cluster}-{new_comm_dict_key}'
    
    
    return cluster_id, comm_id

In [32]:
for index, row in df_chrea_obrist.iterrows():
    cluster_id, comm_id = extract_cluster_community((row.cluster).strip())
    df_cluster_community.iloc[index]['text'] = row.text
    df_cluster_community.iloc[index]['clusterID'] = cluster_id
    df_cluster_community.iloc[index]['communityID'] = comm_id

In [33]:
df_cluster_community

                                                  text clusterID communityID
0    It Wasn't Gas I Passed. The smell was in compa...         1         1-1
1    The Foul Litter box. Whenever I walked into my...         1         1-1
2    I Can't Smell You. I, just tonight, had a cowo...         1         1-1
3    Dragon Breath Teacher. Once a teacher yelled a...         1         1-1
4    The day I took a plunge. I was playing in a fi...         1         1-1
..                                                 ...       ...         ...
434  New car smell. One particular smell experience...         5        5-22
435  New Purse. I had been obsessing over a Marc Ja...         5        5-22
436  Building a PC: A newcomer's experience. I was ...         5        5-22
437  Scent of Skin. Smell of the skin, when growing...         5        5-23
438  Coffee Reborn. The first time I walked into St...         5        5-23

[439 rows x 3 columns]

In [34]:
df_cluster_community.to_csv('./chrea_obrist-ground_truth.csv', index=False)

### cluster_dict

In [35]:
cluster_dict

{'1': 'penetrating',
 '2': 'nauseous',
 '3': 'fresh',
 '4': 'mouthwatering',
 '5': 'attractive'}

In [36]:
# reference table 1: cluster meaning
df_ref_cluster = pd.DataFrame(cluster_dict.items(), columns=['clusterID', 'meaning'])

In [37]:
df_ref_cluster

  clusterID        meaning
0         1    penetrating
1         2       nauseous
2         3          fresh
3         4  mouthwatering
4         5     attractive

In [39]:
df_ref_cluster.to_csv('./chrea_obrist-cluster_reference.csv', index=False)

### cluster_comm_dict

In [40]:
# reference table 2: community meaning
df_ref_community = pd.DataFrame(columns=['communityID', 'meaning'])
df_ref_community

Empty DataFrame
Columns: [communityID, meaning]
Index: []

In [41]:
cluster_comm_dict

{'1': {1: 'affected the social interaction/togetherness',
  2: 'made me change my behaviour',
  3: 'linked to a location',
  4: 'linked to a negative event/episode',
  5: 'linked to a negative life event',
  6: 'helped me to identify it',
  7: 'helped me to detect something',
  8: 'surprised me',
  9: 'traumatized me',
  10: 'overwhelmed me',
  11: 'invaded public space',
  12: 'invaded private space'},
 '2': {1: 'affected the social interaction/togetherness',
  2: 'made me change my mood',
  3: 'coupled to a person',
  4: 'linked to a location',
  5: 'linked to a tradition',
  6: 'linked to a negative event/episode',
  7: 'linked to a negative life event',
  8: 'linked to a positive event/episode',
  9: 'linked to a positive life event',
  10: 'helped me to identify it',
  11: 'helped me to detect something',
  12: 'builds up expectations',
  13: 'surprised me',
  14: 'traumatized me',
  15: 'overwhelmed me',
  16: 'invaded public space',
  17: 'invaded private space',
  18: 'due to first time natural scent',
  19: 'sourced by nature',
  20: 'sourced by food',
  21: 'made me remember a location',
  22: 'made me remember childhood',
  23: 'made me fancy something',
  24: 'triggered newness',
  25: 'triggered reflection'},
 '3': {1: 'affected the social interaction/togetherness',
  2: 'made me change my behaviour',
  3: 'made me change my mood',
  4: 'has been used to change the mood',
  5: 'coupled to first time encounter with a person',
  6: 'coupled to a person',
  7: 'coupled to achievement/success',
  8: 'linked to a new beginning',
  9: 'linked to a location',
  10: 'linked to a tradition',
  11: 'linked to a negative life event',
  12: 'linked to a positive event/episode',
  13: 'linked to a positive life event',
  14: 'helped me to identify it',
  15: 'builds up expectations',
  16: 'surprised me',
  17: 'traumatized me',
  18: 'overwhelmed me',
  19: 'invaded private space',
  20: 'due to first time natural scent',
  21: 'sourced by nature',
  22: 'due to first time food',
  23: 'sourced by food',
  24: 'first time perfume scent',
  25: 'sourced by a perfume',
  26: 'made me remember a location',
  27: 'made me remember a person',
  28: 'made me remember old times teenager/college',
  29: 'made me remember childhood',
  30: 'triggered a flashback',
  31: 'made me do something',
  32: 'made me fancy something',
  33: 'triggered newness'},
 '4': {1: 'affected the social interaction/togetherness',
  2: 'changed my attitude',
  3: 'made me change my behaviour',
  4: 'made me change my mood',
  5: 'coupled to a person',
  6: 'coupled to achievement/success',
  7: 'linked to a new beginning',
  8: 'linked to a location',
  9: 'linked to a tradition',
  10: 'linked to a negative event/episode',
  11: 'linked to a negative life event',
  12: 'linked to a positive event/episode',
  13: 'linked to a positive life event',
  14: 'helped me to identify it',
  15: 'builds up expectations',
  16: 'surprised me',
  17: 'overwhelmed me',
  18: 'invaded public space',
  19: 'invaded private space',
  20: 'sourced by nature',
  21: 'due to first time food',
  22: 'sourced by food',
  23: 'first time perfume scent',
  24: 'sourced by a perfume',
  25: 'made me remember a person',
  26: 'made me remember old times teenager/college',
  27: 'made me remember childhood',
  28: 'triggered a flashback',
  29: 'triggered appetite',
  30: 'made me do something',
  31: 'made me fancy something',
  32: 'triggered newness',
  33: 'caused an aha-moment'},
 '5': {1: 'coupled to first time encounter with a person',
  2: 'coupled to a person',
  3: 'linked to a new beginning',
  4: 'linked to a location',
  5: 'linked to a tradition',
  6: 'linked to a negative event/episode',
  7: 'linked to a positive event/episode',
  8: 'linked to a positive life event',
  9: 'builds up expectations',
  10: 'surprised me',
  11: 'due to first time natural scent',
  12: 'sourced by nature',
  13: 'due to first time food',
  14: 'sourced by food',
  15: 'first time perfume scent',
  16: 'sourced by a perfume',
  17: 'made me remember old times teenager/college',
  18: 'triggered a flashback',
  19: 'triggered appetite',
  20: 'made me do something',
  21: 'made me fancy something',
  22: 'triggered newness',
  23: 'caused an aha-moment'}}

In [42]:
i = 0
for cluster_id, comm_dict in cluster_comm_dict.items():
    for comm_i, meaning in comm_dict.items():
        comm_id = f'{cluster_id}-{comm_i}'
        df_ref_community.at[i, 'communityID'] = comm_id
        df_ref_community.at[i, 'meaning'] = meaning
        i += 1

In [43]:
df_ref_community

    communityID                                       meaning
0           1-1  affected the social interaction/togetherness
1           1-2                   made me change my behaviour
2           1-3                          linked to a location
3           1-4            linked to a negative event/episode
4           1-5               linked to a negative life event
..          ...                                           ...
121        5-19                            triggered appetite
122        5-20                          made me do something
123        5-21                       made me fancy something
124        5-22                             triggered newness
125        5-23                          caused an aha-moment

[126 rows x 2 columns]

In [44]:
df_ref_community.to_csv('./chrea_obrist-community_reference.csv', index=False)

## Making obrist-ground_truth

In [186]:
df_obrist = pd.concat([df_text, obrist[['code_FirstLevel', 'code_SecondLevel']]], axis=1)
df_obrist.columns = ['text', 'firstLevel', 'secondLevel']
df_obrist

,text,firstLevel,secondLevel
0,It Wasn't Gas I Passed. The smell was in compa...,affecting,affected the social interaction/togetherness
1,The Foul Litter box. Whenever I walked into my...,affecting,affected the social interaction/togetherness
2,"I Can't Smell You. I, just tonight, had a cowo...",affecting,affected the social interaction/togetherness
3,Dragon Breath Teacher. Once a teacher yelled a...,affecting,affected the social interaction/togetherness
4,The day I took a plunge. I was playing in a fi...,affecting,affected the social interaction/togetherness
...,...,...,...
434,New car smell. One particular smell experience...,stimulating,triggered newness
435,New Purse. I had been obsessing over a Marc Ja...,stimulating,triggered newness
436,Building a PC: A newcomer's experience. I was ...,stimulating,triggered newness
437,"Scent of Skin. Smell of the skin, when growing...",stimulating,caused an aha-moment
438,Coffee Reborn. The first time I walked into St...,stimulating,caused an aha-moment

In [187]:
first_level = df_obrist.firstLevel.unique()
first_level

array(['affecting', 'changing', 'connecting', 'enabling', 'expecting',
       'hitting/shocking', 'invading', 'pleasing', 'remembering',
       'stimulating'], dtype=object)

In [188]:
len(first_level)

10

In [189]:
second_level = df_obrist.secondLevel.unique()
second_level

array(['affected the social interaction/togetherness',
       'made me change my behaviour', 'made me change my mood',
       'has been used to change the mood', 'changed my attitude',
       'linked to a location', 'linked to a negative event/episode',
       'linked to a negative life event', 'coupled to a person',
       'linked to a tradition', 'linked to a positive event/episode',
       'linked to a positive life event',
       'coupled to first time encounter with a person',
       'coupled to achievement/success', 'linked to a new beginning',
       'helped me to identify it', 'helped me to detect something',
       'surprised me', 'builds up expectations', 'traumatized me',
       'overwhelmed me', 'invaded public space', 'invaded private space',
       'due to first time natural scent', 'sourced by nature',
       'sourced by food', 'due to first time food',
       'first time perfume scent', 'sourced by a perfume',
       'makes me remember a location', 'made me remember childhood',
       'make me remember a person',
       'make me remember old times (teenager/college)',
       'triggered a flashback', 'made me fancy something',
       'triggered newness', 'triggered reflection',
       'made me do something', 'triggered appetite',
       'caused an aha-moment'], dtype=object)

In [190]:
len(second_level)

40

In [191]:
first_level_counts = df_obrist.firstLevel.value_counts().to_frame().reset_index()
first_level_counts.columns = ['firstLevel', 'count']
first_level_counts

         firstLevel  count
0        connecting    157
1          pleasing     62
2       stimulating     49
3       remembering     40
4  hitting/shocking     37
5          invading     32
6          changing     23
7         expecting     17
8          enabling     11
9         affecting     11

In [195]:
df_obrist.secondLevel.value_counts()

linked to a positive event/episode               57
coupled to a person                              24
overwhelmed me                                   22
linked to a location                             22
invaded private space                            22
sourced by nature                                20
sourced by food                                  19
made me remember childhood                       17
linked to a negative event/episode               15
traumatized me                                   15
made me change my behaviour                      14
triggered newness                                13
triggered appetite                               13
made me do something                             12
builds up expectations                           11
affected the social interaction/togetherness     11
triggered a flashback                            10
invaded public space                             10
coupled to first time encounter with a person     9
linked to a positive life event                   8
linked to a negative life event                   8
made me fancy something                           7
made me change my mood                            7
sourced by a perfume                              7
helped me to identify it                          6
linked to a tradition                             6
due to first time food                            6
make me remember a person                         6
surprised me                                      6
due to first time natural scent                   6
helped me to detect something                     5
coupled to achievement/success                    5
first time perfume scent                          4
make me remember old times (teenager/college)     4
makes me remember a location                      3
linked to a new beginning                         3
caused an aha-moment                              3
triggered reflection                              1
has been used to change the mood                  1
changed my attitude                               1
Name: secondLevel, dtype: int64

In [196]:
df_category = pd.DataFrame(
    np.array([
    ["connecting",       "cat1", "Associating the past with a smell"],
    ["pleasing"   ,      "cat3", " Smell perceived as stimulating"],
    ["stimulating" ,     "cat4", " Smell creating desire for more"],
    ["remembering"    ,   "cat2", " Remembering through a smell"],
    ["hitting/shocking",    "cat6", " Overwhelming power of smell"],
    ["invading"         ,   "cat7", " Smell invading private and public space"],
    ["changing"         ,  "cat9", " Smell changes mood, attitude and behavior"],
    ["expecting"        ,   "cat10", " Smell builds up and changes expectations"],
    ["enabling"         , "cat5", " Smell allowing identification and detection"],
    ["affecting"        ,   "cat8", " Social interaction is affected by the smell"]]),
    columns=['firstLevel', 'categoryNumber', 'categoryMeaning']
)
df_category

,firstLevel,categoryNumber,categoryMeaning
0,connecting,cat1,Associating the past with a smell
1,pleasing,cat3,Smell perceived as stimulating
2,stimulating,cat4,Smell creating desire for more
3,remembering,cat2,Remembering through a smell
4,hitting/shocking,cat6,Overwhelming power of smell
5,invading,cat7,Smell invading private and public space
6,changing,cat9,"Smell changes mood, attitude and behavior"
7,expecting,cat10,Smell builds up and changes expectations
8,enabling,cat5,Smell allowing identification and detection
9,affecting,cat8,Social interaction is affected by the smell

In [198]:
ground_truth = df_obrist.merge(df_category, how='left')
# reorder columns
ground_truth = ground_truth[['text', 'categoryNumber', 'categoryMeaning', 'firstLevel', 'secondLevel']]
ground_truth

,text,categoryNumber,categoryMeaning,firstLevel,secondLevel
0,It Wasn't Gas I Passed. The smell was in compa...,cat8,Social interaction is affected by the smell,affecting,affected the social interaction/togetherness
1,The Foul Litter box. Whenever I walked into my...,cat8,Social interaction is affected by the smell,affecting,affected the social interaction/togetherness
2,"I Can't Smell You. I, just tonight, had a cowo...",cat8,Social interaction is affected by the smell,affecting,affected the social interaction/togetherness
3,Dragon Breath Teacher. Once a teacher yelled a...,cat8,Social interaction is affected by the smell,affecting,affected the social interaction/togetherness
4,The day I took a plunge. I was playing in a fi...,cat8,Social interaction is affected by the smell,affecting,affected the social interaction/togetherness
...,...,...,...,...,...
434,New car smell. One particular smell experience...,cat4,Smell creating desire for more,stimulating,triggered newness
435,New Purse. I had been obsessing over a Marc Ja...,cat4,Smell creating desire for more,stimulating,triggered newness
436,Building a PC: A newcomer's experience. I was ...,cat4,Smell creating desire for more,stimulating,triggered newness
437,"Scent of Skin. Smell of the skin, when growing...",cat4,Smell creating desire for more,stimulating,caused an aha-moment
438,Coffee Reborn. The first time I walked into St...,cat4,Smell creating desire for more,stimulating,caused an aha-moment

In [200]:
ground_truth.to_csv('./obrist-ground_truth.csv', index=False)